#!/usr/bin/env python
#
# (The "dcraw_cbrt" variable, a preprocessed list using the
# formula at http://en.wikipedia.org/wiki/CIELAB from
# 0/65535 to 65534/65535, is used in ahd_interpolate().)
#
# It is similar to a cube-root lookup, but not quite.

print '/* automatically generated by gen_dcraw_cbrt.py */'
print 'static const float dcraw_cbrt[0x10000] = {\n ',

def f(t):
	if t > (6./29) ** 3:
		return t**(1./3)
	return 1./3*(29./6)**2*t + 4./29

cbrts = map(lambda x: "%rf" % (64 * f(x/65535.)), xrange(0, 0x10000))
print ',\n  '.join(cbrts)

print '};\n'
