#!/usr/bin/env python
#
# (The "cbrt" variable, a preprocessed list of cube-roots from
# 0/65535 to 65534/65535, is used in ahd_interpolate().)

print '/* automatically generated by gen_dcraw_cbrt.py */'
print 'static const float dcraw_cbrt[0x10000] = {\n ',

cbrts = map(lambda x: "%rf" % (x / 65535.0) ** (1 / 3.), xrange(0, 0x10000))
print ',\n  '.join(cbrts)

print '};\n'
